[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.7"
log = "0.4.27"
rand = "0.9.0"
sdl2 = { version = "0.37.0", features = ["bundled"] }
thiserror = "2.0.12"
